### PR TITLE
fix(Nav Bar): vertical button alignment

### PR DESCRIPTION
**Pull request by andreasgrafen**
partially addresses #89

### CODE REVIEW

**Comment by wiillou** [comment]
this commit did not work for me, however, changing:

[cascade-nav-bar.css] [line:47]

.urlbar-page-action .urlbar-icon { margin-top: 3px !important; }

from 6 to 3 seemed to fix it for me

**Comment by andreasgrafen** [comment]
Yeah.. sometimes it's really weird how pixel values behave on different devices.. I'm looking into another potential rewrite of Cascade in order to get around these issues.

**Comment by wiillou** [comment]
Yea, even with the change i made when i click on the URL bar it goes upwards a bit :c . Kinda annoying that you have to rewrite it to properly fix something like this.

**Comment by andreasgrafen** [comment]
Well, yeah.. But it was an oversight on my end from the start, I guess. So it's just fair that I have to put in work in order to avoid it.

**Pull request merged**
