### PR TITLE
Add padding to tracking protection icon

### PR DESCRIPTION
**Pull request by dybdeskarphet**
I just added padding for tracking protection icon and also a quick explanation for the ones who wants to unhide it.

Here is a comparison screenshot:

### CODE REVIEW

**Comment by andreasgrafen** [comment]
Heya! Thanks a lot for contributing and sorry for the delay. Interestingly enough I personally don't run into this issue on either of my two setups. Just enabling the icon places it correctly. I'll hold off on merging this for now in favour of some further testing as it might potentially be an issue that not everyone experiences. o:

Screenshot 2022-10-01 at 15 04 19 Screenshot 2022-10-01 at 15 04 29

**Comment by dybdeskarphet** [comment]
That's really interesting, thanks for the explanation though!

**Comment by andreasgrafen** [comment]
Heya @dybdeskarphet! Could I ask you a quick favour?
If you could checkout the [rework branch](https://github.com/andreasgrafen/cascade/tree/rework) and let me know if that issue still persists for you? c:

**Comment by dybdeskarphet** [comment]
image
@andreasgrafen problem doesn't persist with rework branch, thank you :)

**Pull request closed without merging**
